# Generated by Django 4.1 on 2022-10-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=20)),
                ('pname', models.CharField(max_length=20)),
                ('rate', models.CharField(max_length=15)),
                ('desc', models.CharField(max_length=50)),
                ('product_Main_img', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
