# Generated by Django 4.1 on 2022-09-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=10)),
                ('femail', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=15)),
                ('message', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
    ]
