# Generated by Django 4.1 on 2022-09-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.CharField(max_length=10)),
                ('rsubject', models.CharField(max_length=15)),
                ('message', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'report',
            },
        ),
    ]
