# Generated by Django 4.1 on 2022-09-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=35)),
                ('cemail', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'contact',
            },
        ),
    ]
