# Generated by Django 4.1 on 2022-10-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_web',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_Main_Img', models.ImageField(upload_to='profile_images/')),
            ],
        ),
    ]
