# Generated by Django 4.1 on 2022-09-26 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=20)),
                ('user_email', models.EmailField(max_length=254)),
                ('curr_pass', models.CharField(max_length=15)),
                ('new_pass', models.CharField(max_length=15)),
                ('con_pass', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
    ]
